import { parseAbi } from 'viem';

// Only the interfaces used by the website. npm test checks these against Forge artifacts.
export default {
  M7Vault: parseAbi([
    'function allowance(address owner, address spender) view returns (uint256)',
    'function approve(address spender, uint256 value) returns (bool)',
    'function backing(uint256 index) view returns (uint256)',
    'function balanceOf(address account) view returns (uint256)',
    'function claimOf(address owner) view returns (uint256[8])',
    'function quoteMint(uint256 sharesOut) view returns (uint256[8] amounts)',
    'function quoteRedeem(uint256 sharesIn) view returns (uint256[8] amounts)',
    'function redeemBasketWithClaims(uint256 sharesIn, uint256[8] minAmounts, address receiver, uint256 deadline) returns (uint256[8] delivered, uint256[8] deferred)',
    'function totalSupply() view returns (uint256)',
    'function withdrawClaim(uint256 index, uint256 amount, address to)',
    'error AlreadyInitialized()',
    'error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)',
    'error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)',
    'error ERC20InvalidApprover(address approver)',
    'error ERC20InvalidReceiver(address receiver)',
    'error ERC20InvalidSender(address sender)',
    'error ERC20InvalidSpender(address spender)',
    'error ExceedsBacking(uint256 index)',
    'error Expired()',
    'error InputLimit(uint256 index)',
    'error InsufficientClaim(uint256 index)',
    'error InsufficientLockedBacking(uint256 index)',
    'error InvalidAmount()',
    'error InvalidConfiguration()',
    'error InvalidIndex()',
    'error InvalidPool(uint256 index)',
    'error InvalidReceiver()',
    'error InvalidSwap()',
    'error MissingComponent(uint256 index)',
    'error NotInitialized()',
    'error OutputLimit(uint256 index)',
    'error PolicyForbidden(uint256 index, bytes32 scope, address account)',
    'error PolicyUnavailable(uint256 index)',
    'error ReentrancyGuardReentrantCall()',
    'error SafeERC20FailedOperation(address token)',
    'error TransferMismatch(uint256 index)',
    'error Unauthorized()',
  ]),
  USDCGateway: parseAbi([
    'function mintWithUSDC(uint256 sharesOut, uint256 maxUSDCIn, address receiver, uint256 deadline) returns (uint256 usdcSpent)',
    'function redeemToUSDC(uint256 sharesIn, uint256 minUSDCOut, address receiver, uint256 deadline) returns (uint256 usdcOut)',
    'error DeadlineExpired()',
    'error InsufficientProceeds()',
    'error InsufficientUSDC()',
    'error InvalidConfiguration()',
    'error InvalidRequest()',
    'error ReentrancyGuardReentrantCall()',
    'error SafeERC20FailedOperation(address token)',
    'error Unauthorized()',
    'error UnexpectedBalance(uint256 assetIndex)',
  ]),
  IndexController: parseAbi([
    'function currentQuarter() view returns (uint32)',
    'function lastExecutedQuarter() view returns (uint32)',
    'function nextTrancheAt() view returns (uint256)',
    'function rebalance(uint256 deadline, address rewardTo)',
    'function rebalanceDue() view returns (bool)',
    'error AlreadyRebalanced()',
    'error EmptyVault()',
    'error Expired()',
    'error InvalidConfiguration()',
    'error InvalidQuarter()',
    'error MissingComponent(uint256 index)',
    'error NoProgress()',
    'error NotCompliant()',
    'error PoolMoved(uint256 index)',
    'error PoolUnavailable(uint256 index)',
    'error RebalanceLoss()',
    'error ReentrancyGuardReentrantCall()',
    'error ResidualCash()',
    'error TooSoon()',
  ]),
  M7Lens: parseAbi([
    'function value() view returns ((uint256 perShare, uint256 nav, uint256 supply, uint256[8] components, uint256 oldestPriceAt, bool issuerPaused, bool sequencerDown) v)',
    'error InvalidConfiguration()',
    'error InvalidPrice(uint256 assetIndex)',
  ]),
  Valuation: parseAbi([
    'function snapshot() view returns (uint256[8] prices)',
    'error CorporateAction(uint256 index)',
    'error InvalidConfiguration()',
    'error NoFreshMarketSignal()',
    'error OutsideExecutionWindow()',
    'error SequencerUnavailable()',
    'error UnavailablePrice(uint256 index)',
  ]),
};
